language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - ~/.platformio
env:
  matrix:
  - PLATFORMIO_CI_SRC="examples/ESPmanager-example" PLATFORMIO_BUILD_FLAGS="-lstdc++" 
  - PLATFORMIO_CI_SRC="examples/ESPmanager-example" PLATFORMIO_BUILD_FLAGS="-D Debug_ESPManager -D DEBUG_ESP_PORT=Serial -lstdc++"
install:
  - pip install -U platformio
  - platformio platforms install espressif --with-package framework-arduinoespressif
  - rm -rf ~/.platformio/packages/framework-arduinoespressif
  - git clone https://github.com/esp8266/Arduino ~/.platformio/packages/framework-arduinoespressif
  - echo "10606" > ~/.platformio/packages/framework-arduinoespressif/version.txt
  - mkdir /tmp/build
  - mkdir $TRAVIS_BUILD_DIR/libs
  - git clone https://github.com/me-no-dev/ESPAsyncTCP                $TRAVIS_BUILD_DIR/libs/ESPAsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncWebServer          $TRAVIS_BUILD_DIR/libs/ESPAsyncWebServer
  - platformio lib install 64

script:
  - platformio ci --board="esp12e" --build-dir="/tmp/build" 
    --lib="." 
    --lib="$TRAVIS_BUILD_DIR/libs/ESPAsyncTCP" 
    --lib="$TRAVIS_BUILD_DIR/libs/ESPAsyncWebServer"
